import React, { useState } from 'react';
import { MonthlyLessonPlan, DailyLessonActivity } from '../../types';
import { useApp } from '../../context/AppContext';
import { X, Calendar, BookOpen, Layers, Sparkles, CheckCircle2, ListPlus } from 'lucide-react';

interface CreateMonthlyPlanModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (plan: Omit<MonthlyLessonPlan, 'id' | 'createdAt'>) => void;
  initialPlan?: MonthlyLessonPlan | null;
}

const MONTHS_LIST = [
  'જૂન ૨૦૨૬',
  'જુલાઈ ૨૦૨૬',
  'ઓગસ્ટ ૨૦૨૬',
  'સપ્ટેમ્બર ૨૦૨૬',
  'ઓક્ટોબર ૨૦૨૬',
  'નવેમ્બર ૨૦૨૬',
  'ડિસેમ્બર ૨૦૨૬',
  'જાન્યુઆરી ૨૦૨૭',
  'ફેબ્રુઆરી ૨૦૨૭',
  'માર્ચ ૨૦૨૭',
  'એપ્રિલ ૨૦૨૭'
];

const STANDARDS_LIST = ['ધોરણ ૩', 'ધોરણ ૪', 'ધોરણ ૫', 'ધોરણ ૬', 'ધોરણ ૭', 'ધોરણ ૮'];
const SUBJECTS_LIST = ['ગણિત', 'વિજ્ઞાન', 'સામાજિક વિજ્ઞાન', 'ગુજરાતી', 'અંગ્રેજી', 'હિન્દી', 'સંસ્કૃત', 'પર્યાવરણ'];

export const CreateMonthlyPlanModal: React.FC<CreateMonthlyPlanModalProps> = ({
  isOpen,
  onClose,
  onSave,
  initialPlan
}) => {
  const { schoolProfile, teacherProfile } = useApp();

  const [month, setMonth] = useState<string>(initialPlan?.month || 'ઓગસ્ટ ૨૦૨૬');
  const [academicYear, setAcademicYear] = useState<string>(initialPlan?.academicYear || '૨૦૨૬-૨૭');
  const [standard, setStandard] = useState<string>(initialPlan?.standard || 'ધોરણ ૭');
  const [division, setDivision] = useState<string>(initialPlan?.division || 'અ');
  const [subject, setSubject] = useState<string>(initialPlan?.subject || 'ગણિત');
  const [teacherName, setTeacherName] = useState<string>(initialPlan?.teacherName || teacherProfile.name || 'શિક્ષક શ્રી');
  const [schoolName, setSchoolName] = useState<string>(initialPlan?.schoolName || schoolProfile.schoolName || 'શ્રી પ્રાથમિક શાળા');
  
  const [unitsInput, setUnitsInput] = useState<string>(
    initialPlan?.unitsCovered.join('\n') || 'પ્રકરણ ૧: સંખ્યા પરિચય\nપ્રકરણ ૨: પૂર્ણ સંખ્યાઓ'
  );
  
  const [learningOutcomesInput, setLearningOutcomesInput] = useState<string>(
    initialPlan?.targetLearningOutcomes.join('\n') || 'LO 1: વિભાવના સ્પષ્ટ કરી વર્ગીકરણ કરે છે.\nLO 2: દૈનિક જીવનના વ્યવહારિક કોયડા ઉકેલે છે.'
  );

  const [generalObjectives, setGeneralObjectives] = useState<string>(
    initialPlan?.generalObjectives || 'વિદ્યાર્થીઓ સંકલ્પના સ્પષ્ટ કરે, TLM દ્વારા પ્રત્યક્ષ અનુભવ મેળવે અને રચનાત્મક મૂલ્યાંકનમાં સારો દેખાવ કરે.'
  );

  const [status, setStatus] = useState<'સક્રિય' | 'પૂર્ણ' | 'ખરડો'>(initialPlan?.status || 'સક્રિય');
  const [autoGenerateDays, setAutoGenerateDays] = useState<boolean>(!initialPlan);
  const [plannedDaysCount, setPlannedDaysCount] = useState<number>(initialPlan?.totalPlannedDays || 6);

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const unitsCovered = unitsInput
      .split('\n')
      .map(u => u.trim())
      .filter(u => u.length > 0);

    const targetLearningOutcomes = learningOutcomesInput
      .split('\n')
      .map(lo => lo.trim())
      .filter(lo => lo.length > 0);

    let dailyActivities: DailyLessonActivity[] = initialPlan?.dailyActivities || [];

    if (!initialPlan && autoGenerateDays) {
      // Auto-generate template daily activities with realistic checkable subtasks!
      dailyActivities = Array.from({ length: plannedDaysCount }, (_, idx) => {
        const dayNo = idx + 1;
        const mainUnit = unitsCovered[Math.min(Math.floor(idx / 3), unitsCovered.length - 1)] || `પ્રકરણ ${idx + 1}`;
        return {
          id: `da-gen-${Date.now()}-${dayNo}`,
          dayNumber: dayNo,
          date: new Date(Date.now() + idx * 86400000 * 2).toISOString().split('T')[0],
          periodNumber: (dayNo % 4) + 1,
          title: `દિવસ ${dayNo}: ${mainUnit} - ભાગ ${((idx % 3) + 1)}`,
          topic: `${mainUnit} ની વિભાવના અને મહાવરો`,
          learningOutcome: targetLearningOutcomes[Math.min(idx, targetLearningOutcomes.length - 1)] || 'અધ્યયન નિષ્પત્તિ દ્રઢીકરણ',
          teachingActivity: `વર્ગખંડમાં TLM, ચાર્ટ અને પ્રશ્નોત્તરી પદ્ધતિ દ્વારા ${mainUnit} નું રસપ્રદ શિક્ષણ કાર્ય કરાવવું.`,
          tlmUsed: 'પાઠ્યપુસ્તક, શૈક્ષણિક ચાર્ટ, ગ્રીડ શીટ, ડિજિટલ સાધન',
          assessmentMethod: 'મૌખિક પ્રશ્નોત્તરી અને સ્લેટ વર્ક',
          homework: `સ્વાધ્યાયના પ્રશ્નો ૧ થી ${dayNo + 2} નોટબુકમાં ગણવા`,
          status: dayNo === 1 ? 'ચાલુ' : 'આયોજિત',
          subTasks: [
            { id: `st-g-${dayNo}-1`, taskTitle: 'પૂર્વજ્ઞાન ચકાસણી & પરિચય પ્રશ્નોત્તરી', isCompleted: dayNo === 1 },
            { id: `st-g-${dayNo}-2`, taskTitle: 'TLM અને વિષયવસ્તુનું વર્ગખંડ નિદર્શન', isCompleted: false },
            { id: `st-g-${dayNo}-3`, taskTitle: 'વિદ્યાર્થીઓ દ્વારા જોડીમાં સ્વાધ્યાય પ્રેક્ટિસ', isCompleted: false },
            { id: `st-g-${dayNo}-4`, taskTitle: 'મુશ્કેલી નિવારણ અને ઉપચારાત્મક કાર્ય', isCompleted: false },
            { id: `st-g-${dayNo}-5`, taskTitle: 'ગૃહકાર્ય નોંધ અને શિક્ષક ડાયરી લેખન', isCompleted: false }
          ]
        };
      });
    }

    onSave({
      month,
      academicYear,
      standard,
      division,
      subject,
      teacherName,
      schoolName,
      unitsCovered: unitsCovered.length > 0 ? unitsCovered : ['સામાન્ય પુનરાવર્તન'],
      totalPlannedDays: dailyActivities.length || plannedDaysCount,
      targetLearningOutcomes: targetLearningOutcomes.length > 0 ? targetLearningOutcomes : ['સામાન્ય અધ્યયન નિષ્પત્તિ'],
      generalObjectives,
      status,
      dailyActivities
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-3xl overflow-hidden my-8 animate-in fade-in zoom-in-95 duration-200">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 bg-gradient-to-r from-emerald-700 to-teal-800 text-white">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center backdrop-blur-xs border border-white/20">
              <Calendar className="w-5 h-5 text-emerald-200" />
            </div>
            <div>
              <h3 className="text-lg font-bold">
                {initialPlan ? 'માસિક પાઠ આયોજન સુધારો (Edit Monthly Plan)' : 'નવું માસિક પાઠ આયોજન (Create Monthly Plan)'}
              </h3>
              <p className="text-xs text-emerald-100">
                માસવાર વિષય આયોજન અને દૈનિક પ્રવૃત્તિનું માળખું
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-white/80 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
          {/* Row 1: Month, Academic Year, Standard, Division */}
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">માસ (Month) *</label>
              <select
                value={month}
                onChange={e => setMonth(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden bg-white"
              >
                {MONTHS_LIST.map(m => (
                  <option key={m} value={m}>{m}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">શૈક્ષણિક વર્ષ</label>
              <input
                type="text"
                value={academicYear}
                onChange={e => setAcademicYear(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">ધોરણ (Standard) *</label>
              <select
                value={standard}
                onChange={e => setStandard(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden bg-white"
              >
                {STANDARDS_LIST.map(s => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">વર્ગ / વર્ગખંડ</label>
              <input
                type="text"
                value={division}
                onChange={e => setDivision(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden"
              />
            </div>
          </div>

          {/* Row 2: Subject, Teacher Name, Status */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">વિષય (Subject) *</label>
              <select
                value={subject}
                onChange={e => setSubject(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden bg-white"
              >
                {SUBJECTS_LIST.map(sub => (
                  <option key={sub} value={sub}>{sub}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">શિક્ષકનું નામ</label>
              <input
                type="text"
                value={teacherName}
                onChange={e => setTeacherName(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">આયોજન સ્થિતિ (Status)</label>
              <select
                value={status}
                onChange={e => setStatus(e.target.value as any)}
                className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden bg-white"
              >
                <option value="સક્રિય">સક્રિય (Active)</option>
                <option value="પૂર્ણ">પૂર્ણ (Completed)</option>
                <option value="ખરડો">ખરડો (Draft)</option>
              </select>
            </div>
          </div>

          {/* Row 3: Units Covered (One per line) */}
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              સમાવિષ્ટ એકમો / પ્રકરણો (Units / Chapters Covered) - દર લીટીએ એક પ્રકરણ
            </label>
            <textarea
              rows={2}
              required
              placeholder="પ્રકરણ ૧: પૂર્ણાંક સંખ્યાઓ&#10;પ્રકરણ ૨: અપૂર્ણાંક અને દશાંશ સંખ્યાઓ"
              value={unitsInput}
              onChange={e => setUnitsInput(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden font-mono text-xs"
            />
          </div>

          {/* Row 4: Learning Outcomes */}
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              લક્ષિત અધ્યયન નિષ્પત્તિઓ (Target Learning Outcomes) - દર લીટીએ એક
            </label>
            <textarea
              rows={2}
              placeholder="M701: સંખ્યારેખા પર પૂર્ણાંક સંખ્યા દર્શાવે છે&#10;M702: પૂર્ણાંક સંખ્યાઓના સરવાળા અને બાદબાકી નિયમો લાગુ કરે છે"
              value={learningOutcomesInput}
              onChange={e => setLearningOutcomesInput(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden font-mono text-xs"
            />
          </div>

          {/* Row 5: General Objectives */}
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">સામાન્ય હેતુઓ / શૈક્ષણિક વિઝન</label>
            <textarea
              rows={2}
              value={generalObjectives}
              onChange={e => setGeneralObjectives(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:outline-hidden"
            />
          </div>

          {/* Auto-generate initial days option (only when creating new) */}
          {!initialPlan && (
            <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-3 flex items-center justify-between">
              <div className="flex items-center space-x-2.5">
                <Sparkles className="w-5 h-5 text-emerald-600" />
                <div>
                  <h4 className="text-xs font-bold text-emerald-900">
                    દૈનિક પ્રવૃત્તિઓ અને પેટા-કાર્યો આપમેળે બનાવો (Auto-generate Daily Breakdown)
                  </h4>
                  <p className="text-[11px] text-emerald-700">
                    પસંદ કરેલ વિષય અને પ્રકરણ આધારિત તૈયાર દૈનિક ચેકલિસ્ટ સાથે શરૂ કરો
                  </p>
                </div>
              </div>
              <div className="flex items-center space-x-2">
                <label className="text-xs font-semibold text-emerald-900">દિવસો:</label>
                <select
                  value={plannedDaysCount}
                  onChange={e => setPlannedDaysCount(parseInt(e.target.value) || 6)}
                  className="px-2 py-1 text-xs border border-emerald-300 rounded-lg bg-white font-bold"
                >
                  <option value={4}>૪ દિવસ (4 Days)</option>
                  <option value={6}>૬ દિવસ (6 Days)</option>
                  <option value={8}>૮ દિવસ (8 Days)</option>
                  <option value={10}>૧૦ દિવસ (10 Days)</option>
                  <option value={12}>૧૨ દિવસ (12 Days)</option>
                </select>
                <input
                  type="checkbox"
                  checked={autoGenerateDays}
                  onChange={e => setAutoGenerateDays(e.target.checked)}
                  className="w-4 h-4 text-emerald-600 rounded-sm"
                />
              </div>
            </div>
          )}

          {/* Form Actions */}
          <div className="flex items-center justify-end space-x-3 pt-3 border-t border-slate-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-semibold text-slate-600 hover:text-slate-800 bg-slate-100 hover:bg-slate-200 rounded-xl cursor-pointer"
            >
              રદ કરો (Cancel)
            </button>
            <button
              type="submit"
              className="px-5 py-2 text-xs font-bold text-white bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 rounded-xl shadow-md cursor-pointer"
            >
              {initialPlan ? 'આયોજન સાચવો (Update Plan)' : 'માસિક આયોજન બનાવો (Create Plan)'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
